### ISSUE TITLE
rsnaphot node 

### ISSUE THREAD

**Issue by beatu** [ivaldi/ivaldi-rsnapshot#3]
I am trying to use foreman to install the rsnapshot puppet module. I am new to both Foreman and Puppet. The rsnapshot backup master installs correctly but the node does not add the ssh public key of the rsnapshot master to the authorized_keys file of root (no error shown)

**Comment by frenkel** [comment]
Did you setup exported resources? If not, first [install PuppetDB](https://docs.puppetlabs.com/puppetdb/latest/install_via_module.html) and then [configure your master to connect to it](https://docs.puppetlabs.com/puppetdb/latest/connect_puppet_master.html)
